project:
  type: book
  output-dir: _book

book:
  title: "AGDS 2: Digital Soil Mapping"
  subtitle: "Predicting soil properties from spatial data"
  author: 
    - name: "Pascal Schneider"
    - name: "Madlene Nussbaum"
  date: "6/29/2023"
  page-navigation: true
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-data_preparation.qmd
    - 03-model_fit.qmd
    - 04-model_eval.qmd
    - 99-exercise.qmd
    - references.qmd
  search: true
  navbar: 
    right:
      - icon: github
        href: https://github.com/padasch/digital_soil_mapping
        aria-label: GitHub
  
bibliography: references.bib
csl: global-change-biology.csl

format:
  html:
    theme: cosmo
    code-fold: true
    code-copy: true
    code-summary: "Show/Hide Code"
  # pdf:
  #   documentclass: scrreprt

editor: visual

execute: 
  warning: false
  freeze: auto
